/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as UserTakeQuizRouteImport } from './routes/user/takeQuiz'
import { Route as UserQuizModificationpostIDRouteImport } from './routes/user/quizModification$postID'
import { Route as UserQuizRouteImport } from './routes/user/quiz'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTakeQuizRoute = UserTakeQuizRouteImport.update({
  id: '/user/takeQuiz',
  path: '/user/takeQuiz',
  getParentRoute: () => rootRouteImport,
} as any)
const UserQuizModificationpostIDRoute =
  UserQuizModificationpostIDRouteImport.update({
    id: '/user/quizModification$postID',
    path: '/user/quizModification$postID',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserQuizRoute = UserQuizRouteImport.update({
  id: '/user/quiz',
  path: '/user/quiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user/quiz': typeof UserQuizRoute
  '/user/quizModification$postID': typeof UserQuizModificationpostIDRoute
  '/user/takeQuiz': typeof UserTakeQuizRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user/quiz': typeof UserQuizRoute
  '/user/quizModification$postID': typeof UserQuizModificationpostIDRoute
  '/user/takeQuiz': typeof UserTakeQuizRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user/quiz': typeof UserQuizRoute
  '/user/quizModification$postID': typeof UserQuizModificationpostIDRoute
  '/user/takeQuiz': typeof UserTakeQuizRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/user/quiz'
    | '/user/quizModification$postID'
    | '/user/takeQuiz'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/user/quiz'
    | '/user/quizModification$postID'
    | '/user/takeQuiz'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/user/quiz'
    | '/user/quizModification$postID'
    | '/user/takeQuiz'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UserQuizRoute: typeof UserQuizRoute
  UserQuizModificationpostIDRoute: typeof UserQuizModificationpostIDRoute
  UserTakeQuizRoute: typeof UserTakeQuizRoute
  UserIndexRoute: typeof UserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/takeQuiz': {
      id: '/user/takeQuiz'
      path: '/user/takeQuiz'
      fullPath: '/user/takeQuiz'
      preLoaderRoute: typeof UserTakeQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/quizModification$postID': {
      id: '/user/quizModification$postID'
      path: '/user/quizModification$postID'
      fullPath: '/user/quizModification$postID'
      preLoaderRoute: typeof UserQuizModificationpostIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/quiz': {
      id: '/user/quiz'
      path: '/user/quiz'
      fullPath: '/user/quiz'
      preLoaderRoute: typeof UserQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UserQuizRoute: UserQuizRoute,
  UserQuizModificationpostIDRoute: UserQuizModificationpostIDRoute,
  UserTakeQuizRoute: UserTakeQuizRoute,
  UserIndexRoute: UserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
