/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as QuizQuizIDRouteImport } from './routes/quiz/$quizID'
import { Route as QuizTakeQuizQuizIDRouteImport } from './routes/quiz/takeQuiz/$quizID'
import { Route as QuizQuizModificationQuizIDRouteImport } from './routes/quiz/quizModification/$quizID'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIDRoute = QuizQuizIDRouteImport.update({
  id: '/quiz/$quizID',
  path: '/quiz/$quizID',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTakeQuizQuizIDRoute = QuizTakeQuizQuizIDRouteImport.update({
  id: '/quiz/takeQuiz/$quizID',
  path: '/quiz/takeQuiz/$quizID',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizModificationQuizIDRoute =
  QuizQuizModificationQuizIDRouteImport.update({
    id: '/quiz/quizModification/$quizID',
    path: '/quiz/quizModification/$quizID',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/quiz/$quizID': typeof QuizQuizIDRoute
  '/user/': typeof UserIndexRoute
  '/quiz/quizModification/$quizID': typeof QuizQuizModificationQuizIDRoute
  '/quiz/takeQuiz/$quizID': typeof QuizTakeQuizQuizIDRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/quiz/$quizID': typeof QuizQuizIDRoute
  '/user': typeof UserIndexRoute
  '/quiz/quizModification/$quizID': typeof QuizQuizModificationQuizIDRoute
  '/quiz/takeQuiz/$quizID': typeof QuizTakeQuizQuizIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/quiz/$quizID': typeof QuizQuizIDRoute
  '/user/': typeof UserIndexRoute
  '/quiz/quizModification/$quizID': typeof QuizQuizModificationQuizIDRoute
  '/quiz/takeQuiz/$quizID': typeof QuizTakeQuizQuizIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/quiz/$quizID'
    | '/user/'
    | '/quiz/quizModification/$quizID'
    | '/quiz/takeQuiz/$quizID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/quiz/$quizID'
    | '/user'
    | '/quiz/quizModification/$quizID'
    | '/quiz/takeQuiz/$quizID'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/quiz/$quizID'
    | '/user/'
    | '/quiz/quizModification/$quizID'
    | '/quiz/takeQuiz/$quizID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  QuizQuizIDRoute: typeof QuizQuizIDRoute
  UserIndexRoute: typeof UserIndexRoute
  QuizQuizModificationQuizIDRoute: typeof QuizQuizModificationQuizIDRoute
  QuizTakeQuizQuizIDRoute: typeof QuizTakeQuizQuizIDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizID': {
      id: '/quiz/$quizID'
      path: '/quiz/$quizID'
      fullPath: '/quiz/$quizID'
      preLoaderRoute: typeof QuizQuizIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/takeQuiz/$quizID': {
      id: '/quiz/takeQuiz/$quizID'
      path: '/quiz/takeQuiz/$quizID'
      fullPath: '/quiz/takeQuiz/$quizID'
      preLoaderRoute: typeof QuizTakeQuizQuizIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/quizModification/$quizID': {
      id: '/quiz/quizModification/$quizID'
      path: '/quiz/quizModification/$quizID'
      fullPath: '/quiz/quizModification/$quizID'
      preLoaderRoute: typeof QuizQuizModificationQuizIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  QuizQuizIDRoute: QuizQuizIDRoute,
  UserIndexRoute: UserIndexRoute,
  QuizQuizModificationQuizIDRoute: QuizQuizModificationQuizIDRoute,
  QuizTakeQuizQuizIDRoute: QuizTakeQuizQuizIDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
